fix config path - do not make backups on destroy

diff --git a/debian/vzctl.preinst b/debian/vzctl.preinst
--- a/debian/vzctl.preinst
+++ b/debian/vzctl.preinst
@@ -23,6 +23,17 @@ case "$1" in
 	    rm -f "/etc/network/if-up.d/vzifup-post"
 	fi
 
+	# move old config out of the way - newer version
+	# use a symlink to /etc/pve/openvz
+	if [ ! -L "/etc/vz/conf" ]; then
+	    if [ -e "/etc/vz/conf.org" ]; then
+		echo "unable to backup existing configuration"
+		exit 1
+	    fi
+	    mv /etc/vz/conf /etc/vz/conf.org
+	    ln -s /etc/pve/openvz /etc/vz/conf
+	fi
+
 	# compability mode /var/lib/vz -> /vz
 	# ln -sT /var/lib/vz vz 2>/dev/null || true
 	# echo "Add a link from /var/lib/vz to /vz/"
